### ISSUE TITLE
Insert Null Checkbox Issue

### ISSUE THREAD

**Issue by karamcintyre** [SFDO-Community/Interactions-for-Student-Recruitment#12]
The Insert Null functionality does not support check boxes in the correct way. A false checkbox should be treated as a null, allowing an Interaction Mapping to set it to false if "Insert Null" is checked. This will be addressed in our next update of the package.

**Comment by meruff** [comment]
@karamcintyre I've pushed up the changes we've been testing, I'll open a PR.
