### ISSUE TITLE
it doesn't matter which Opp Stage I select it always creates/updates the Applicant Opportunity

### ISSUE THREAD

**Issue by robertwynter** [SFDO-Community/Interactions-for-Student-Recruitment#19]
my issues are coming from the Interaction object as that's where I'm entering the records. When we create a new record via the Interaction object. Based on the value selected in the field option "Opportunity stage". According to the video demo. If Inquiry is select then the Opportunity create/updated should be "Inquiry Opportunity" and if the value selected is Applied then it should create/update the Applicant Opportunity. My issue is that it doesn't matter which one I select it always creates/updates the Applicant Opportunity.

**Comment by debbieduran** [comment]
Resolved with admin configuration at both the page layout and profile by requester. Posted solution in PUB.
